version: "2"
services:
  test:
    container_name: assignment-app-test
    build: ./
    command: pytest
  app:
    container_name: assignment-app
    build: ./
    ports:
    - 7000:7000
    environment:
      - PYTHON_ENV=production
